<div>
<script>

// JavaScriptの例外処理 try-catch-finally文とthrow new Error の使い方


let robotama = null

// 1. try-ブロック => 通常の処理を記述する
try {

    let id = robotama.id;

// 2. catch-ブロック => 異常系の処理インターファイスを記述する
} catch (error) {

    // Error-Objectから、Error-メッセージだけを出力している
    console.log(error.message);

    // Error-Level で Error-Objectをそのまま出力している
    console.error(error);


// 3. finally-ブロック => Success か Error かに関わらず、実行する処理を記述する！
// finally-ブロックの中に書いたコードは、 try および catch ブロックの後で常に実行されます。
} finally {
    console.log('神聖グンマー帝国、万歳！');
}

const SaitamaNoSpy = {
    id: 1,
    robotama: 'ロボ玉',
    like: 'ひまたね',
    yama: '富士山',
    from: 'さいたまー共和国',
}

const Gunmar = {
    id: 2,
    robotama: 'ジョニー・ジョコビッチ (JoJo)',
    like: '焼きまんじゅう',
    yama: '赤城山',
    from: '神聖グンマー帝国',
}

const GunmarCheck = (key, val) => {

    // 1. try-ブロック => 通常の処理を記述する
    try {


        // 1-1. グンマーの民かどうかを試すブロック
        if (key == 'from' && val !== '神聖グンマー帝国') {
            const error1 = new Error('お前、グンマーじゃないな・・・');
            alert(error1.message);

            throw error1;
        }

        if (key == 'yama' && val !== '赤城山') {
            const error2 = new Error('グンマー帝国の山は、赤城山だ！');
            alert(error2.message);

            throw error2;
        }

        if (key == 'like' && val !== '焼きまんじゅう') {

            const error3 = new Error('故郷の味は、焼きまんじゅう！');
            alert(error3.message);

            throw error3;
        }


        // 1-2. 無事に、グンマーの民、Checkをクリアしたらここまで来れる！
        
        // throw new Error で、catch-ブロックに飛ばなければ、ここの console.logが出力される。
        console.log(key, val);


    // 2. catch-ブロック => 異常系の処理インターファイスを記述する
    } catch (error) {

        // Error-Objectから、Error-メッセージだけを出力している
        console.warn(error.message);

        // Error-Level で Error-Objectをそのまま出力している
        console.error(error);
    }
}


for (const key in  SaitamaNoSpy) {
    const val = SaitamaNoSpy[key];
    GunmarCheck(key, val);
}


for (const key in  Gunmar) {
    const val = Gunmar[key];
    GunmarCheck(key, val);
}


</script>
</div>
